topic-toproducer: tointent
broker-id: 172.23.239.165:9092
#topic-toproducer: tointent
topic-fromconsumer: testcontrol
spring:
 application:
   name: crawlerservice
 cloud:
    config:
      uri: http://localhost:8888

 