server:
 port: 8080
 
#ribbon:
# erueka:
#   enabled: false
#    
search:
  ribbon:  
    listOfServers: localhost:8060,localhost:8061,localhost:8062
    ServerListRefreshInterval: 15000 
    
crawler:
  ribbon:  
    listOfServers: localhost:8070,localhost:8071,localhost:8072
    ServerListRefreshInterval: 15000     